services:
  ha-fusion:
    container_name: ha-fusion
    image: ghcr.io/matt8707/ha-fusion
    volumes:
      - /path/to/ha-fusion:/app/data
    network_mode: bridge
    ports:
      - 5050:5050
    environment:
      TZ: Europe/Bucharest
      HASS_URL: http://192.168.1.210:8123
    restart: always
